In [ ]:
df.columns
df.indexes
df.dtypes
df.shape
df.describe()
df.shape[0]
df.head(5)
df.tail(5)
df.unique()
df.nunique()
pd.DataFrame({'Company':['TCS','HCL']})
df.index=['First','second','Third']
df.reset_index(inplace=True)
df.loc[['Second','Fourth']] # string indices
df.iloc[[3,4]] # integer indices
furniture.cost=furniture['Cost'].astype(float)
furniture.value_counts()
df.set_index('Company') # set one column as index
df.sort_values('Cost',ascending=False)
df.columns=['Col1','Col2','Col3'] # to rename the column names
df
# or
df.rename(columns={'Product':'Category'}, inplace=True)
df.drop('Col1', axis=1)
df.dropna()
df.fillna(method='ffill') #bfill
df.isnull()
df.isnull().sum()

In [2]:
import pandas as pd
df=pd.read_csv('projects_data.csv')

/home/ankur/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (44) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
df.head()

,id,regionname,countryname,prodline,lendinginstr,lendinginstrtype,envassesmentcategorycode,supplementprojectflg,productlinetype,projectstatusdisplay,...,mjtheme3name,mjtheme4name,mjtheme5name,location,GeoLocID,GeoLocName,Latitude,Longitude,Country,Unnamed: 56
0,P162228,Other,World;World,RE,Investment Project Financing,IN,C,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P163962,Africa,Democratic Republic of the Congo;Democratic Re...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P167672,South Asia,People's Republic of Bangladesh;People's Repub...,PE,Investment Project Financing,IN,NaN,Y,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,P158768,South Asia,Islamic Republic of Afghanistan;Islamic Repu...,PE,Investment Project Financing,IN,A,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,P161364,Africa,Federal Republic of Nigeria;Federal Republic o...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,0002327546!$!Ogun State!$!7!$!3.58333!$!NG;000...,0002327546;0002328925;0002565340;0002565343;00...,Ogun State;Niger State;Abia State;Edo;Kebbi St...,7;10;5.41667;6.5;11.5;8,3.58333;6;7.5;6;4;10.5,NG;NG;NG;NG;NG;NG,NaN

In [4]:
df['regionname'].unique()

array(['Other', 'Africa', 'South Asia', 'Middle East and North Africa',
       'Europe and Central Asia', 'East Asia and Pacific',
       'Latin America and Caribbean'], dtype=object)

In [5]:
df['regionname'].nunique()

7

In [3]:
import pandas as pd
li=[{'name':'John','age':32,'org':'TCS'},{'name':'Mike','age':33,'org':'HCL'}]

In [4]:
df_test=pd.DataFrame.from_dict(li)

In [5]:
df_test

   age  name  org
0   32  John  TCS
1   33  Mike  HCL

In [6]:
df_test['Sal']=pd.Series([2000,3000])

In [7]:
df_test

   age  name  org   Sal
0   32  John  TCS  2000
1   33  Mike  HCL  3000

In [9]:
df_test['sum']=df_test['age']+df_test['Sal']
df_test

   age  name  org   Sal   sum
0   32  John  TCS  2000  2032
1   33  Mike  HCL  3000  3033

In [14]:
df_test.index

RangeIndex(start=0, stop=2, step=1)

In [15]:
df_test.index=['First','Second']

In [16]:
df_test

        age  name  org
First    32  John  TCS
Second   33  Mike  HCL

## encodings

In [17]:
import pandas as pd
df_mystery=pd.read_csv('mystery.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

In [18]:
from encodings.aliases import aliases

alias_values = set(aliases.values())


for encoding in alias_values:
    try:
        df=pd.read_csv('mystery.csv', encoding=encoding)
        print('successful', encoding)
    except:
        pass

{'utf_32_le', 'koi8_r', 'iso2022_jp_3', 'euc_jp', 'cp1255', 'cp775', 'tactis', 'cp1125', 'cp1254', 'cp855', 'mac_latin2', 'shift_jis', 'bz2_codec', 'quopri_codec', 'cp1253', 'latin_1', 'johab', 'cp500', 'gbk', 'gb2312', 'mac_greek', 'cp037', 'cp862', 'hz', 'iso2022_jp_2004', 'cp273', 'iso8859_8', 'iso8859_11', 'cp861', 'cp437', 'mbcs', 'cp858', 'cp1251', 'kz1048', 'uu_codec', 'cp1258', 'rot_13', 'iso8859_15', 'ascii', 'cp1257', 'cp866', 'euc_kr', 'tis_620', 'iso8859_7', 'euc_jisx0213', 'cp850', 'utf_32', 'iso8859_14', 'mac_cyrillic', 'hp_roman8', 'cp424', 'iso2022_jp', 'mac_roman', 'utf_7', 'iso2022_kr', 'iso8859_2', 'utf_32_be', 'mac_iceland', 'utf_8', 'cp869', 'iso8859_4', 'iso8859_5', 'gb18030', 'cp932', 'iso8859_6', 'zlib_codec', 'cp1256', 'cp857', 'cp852', 'iso8859_9', 'euc_jis_2004', 'cp865', 'utf_16_le', 'base64_codec', 'iso2022_jp_ext', 'hex_codec', 'cp1250', 'utf_16_be', 'big5', 'cp1140', 'cp949', 'iso2022_jp_2', 'iso8859_10', 'shift_jisx0213', 'shift_jis_2004', 'utf_16', 'iso2022_jp_1', 'iso8859_16', 'cp950', 'iso8859_3', 'cp1026', 'cp1252', 'cp864', 'cp863', 'big5hkscs', 'mac_turkish', 'cp860', 'ptcp154', 'iso8859_13'}
successful utf_16_le
successful utf_16_be
successful utf_16

## datatypes

In [33]:
import pandas as pd

# read in the population data and drop the final column
df_indicator = pd.read_csv('population_data.csv', skiprows=4)
pd.set_option('display.max_columns',1000)

In [34]:
df_indicator.head(2)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
0,Aruba,ABW,"Population, total",SP.POP.TOTL,"54,211","55,438","56,225","56,695","57,032","57,360","57,715","58,055","58,386","58,726","59,063","59,440","59,840","60,243","60,528","60,657","60,586","60,366","60,103","59,980","60,096","60,567","61,345","62,201","62,836","63,026","62,644","61,833","61,079","61,032","62,149","64,622","68,235","72,504","76,700","80,324","83,200","85,451","87,277","89,005","90,853","92,898","94,992","97,017","98,737","100,031","100,832","101,220","101,353","101,453","101,669","102,053","102,577","103,187","103,795","104,341","104,822","105,264",nan
1,Afghanistan,AFG,"Population, total",SP.POP.TOTL,"8,996,351","9,166,764","9,345,868","9,533,954","9,731,361","9,938,414","10,152,331","10,372,630","10,604,346","10,854,428","11,126,123","11,417,825","11,721,940","12,027,822","12,321,541","12,590,286","12,840,299","13,067,538","13,237,734","13,306,695","13,248,370","13,053,954","12,749,645","12,389,269","12,047,115","11,783,050","11,601,041","11,502,761","11,540,888","11,777,609","12,249,114","12,993,657","13,981,231","15,095,099","16,172,719","17,099,541","17,822,884","18,381,605","18,863,999","19,403,676","20,093,756","20,966,463","21,979,923","23,064,851","24,118,979","25,070,798","25,893,450","26,616,792","27,294,031","28,004,331","28,803,167","29,708,599","30,696,958","31,731,688","32,758,020","33,736,494","34,656,032","35,530,081",nan

In [26]:
df_indicator.drop(['Unnamed: 62'], axis=1, inplace=True)

In [27]:
df_indicator.dtypes

Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960              float64
1961              float64
1962              float64
1963              float64
1964              float64
1965              float64
1966              float64
1967              float64
1968              float64
1969              float64
1970              float64
1971              float64
1972              float64
1973              float64
1974              float64
1975              float64
1976              float64
1977              float64
1978              float64
1979              float64
1980              float64
1981              float64
1982              float64
1983              float64
1984              float64
1985              float64
                   ...
1988              float64
1989              float64
1990              float64
1991              float64
1992              float64
1993              float64
1994              float64
1995              float64
1996              float64
1997              float64
1998              float64
1999              float64
2000              float64
2001              float64
2002              float64
2003              float64
2004              float64
2005              float64
2006              float64
2007              float64
2008              float64
2009              float64
2010              float64
2011              float64
2012              float64
2013              float64
2014              float64
2015              float64
2016              float64
2017              float64
Length: 62, dtype: object

In [30]:
# to change the float output into int
pd.options.display.float_format = '{:,.0f}'.format

In [35]:
df_nafta=df_indicator[(df_indicator['Country Name']=='Mexico') | (df_indicator['Country Name']=='Canada') |
                     (df_indicator['Country Name']=='United States')]

In [38]:
df_nafta

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
33,Canada,CAN,"Population, total",SP.POP.TOTL,"17,909,009","18,271,000","18,614,000","18,964,000","19,325,000","19,678,000","20,048,000","20,412,000","20,744,000","21,028,000","21,324,000","21,645,535","21,993,631","22,369,408","22,774,087","23,209,000","23,518,000","23,796,000","24,036,000","24,277,000","24,593,000","24,900,000","25,202,000","25,456,000","25,702,000","25,942,000","26,204,000","26,550,000","26,895,000","27,379,000","27,791,000","28,171,682","28,519,597","28,833,410","29,111,906","29,354,000","29,671,900","29,987,200","30,247,900","30,499,200","30,769,700","31,081,900","31,362,000","31,676,000","31,995,000","32,312,000","32,570,505","32,887,928","33,245,773","33,628,571","34,005,274","34,342,780","34,750,545","35,152,370","35,535,348","35,832,513","36,264,604","36,708,083",nan
152,Mexico,MEX,"Population, total",SP.POP.TOTL,"38,174,112","39,394,126","40,649,588","41,939,880","43,264,272","44,623,043","46,011,038","47,429,812","48,894,019","50,423,481","52,029,861","53,718,724","55,478,151","57,280,587","59,088,193","60,872,399","62,623,763","64,345,884","66,039,488","67,709,689","69,360,871","70,992,195","72,602,533","74,196,548","75,780,605","77,360,707","78,934,125","80,503,052","82,083,919","83,697,891","85,357,874","87,071,512","88,828,310","90,600,453","92,349,147","94,045,579","95,687,452","97,281,739","98,821,456","100,300,579","101,719,673","103,067,068","104,355,608","105,640,453","106,995,583","108,472,228","110,092,378","111,836,346","113,661,809","115,505,228","117,318,941","119,090,017","120,828,307","122,535,969","124,221,600","125,890,949","127,540,423","129,163,276",nan
249,United States,USA,"Population, total",SP.POP.TOTL,"180,671,000","183,691,000","186,538,000","189,242,000","191,889,000","194,303,000","196,560,000","198,712,000","200,706,000","202,677,000","205,052,000","207,661,000","209,896,000","211,909,000","213,854,000","215,973,000","218,035,000","220,239,000","222,585,000","225,055,000","227,225,000","229,466,000","231,664,000","233,792,000","235,825,000","237,924,000","240,133,000","242,289,000","244,499,000","246,819,000","249,623,000","252,981,000","256,514,000","259,919,000","263,126,000","266,278,000","269,394,000","272,657,000","275,854,000","279,040,000","282,162,411","284,968,955","287,625,193","290,107,933","292,805,298","295,516,599","298,379,912","301,231,207","304,093,966","306,771,529","309,338,421","311,644,280","313,993,272","316,234,505","318,622,525","321,039,839","323,405,935","325,719,178",nan

In [43]:
keepcol = ['Country Name']
for i in range(1960, 2018, 1):
    keepcol.append(str(i))
keepcol    
df_nafta.sum(axis=0)[keepcol]

Country Name    CanadaMexicoUnited States
1960                          236,754,121
1961                          241,356,126
1962                          245,801,588
1963                          250,145,880
1964                          254,478,272
1965                          258,604,043
1966                          262,619,038
1967                          266,553,812
1968                          270,344,019
1969                          274,128,481
1970                          278,405,861
1971                          283,025,259
1972                          287,367,782
1973                          291,558,995
1974                          295,716,280
1975                          300,054,399
1976                          304,176,763
1977                          308,380,884
1978                          312,660,488
1979                          317,041,689
1980                          321,178,871
1981                          325,358,195
1982                          329,468,533
1983                          333,444,548
1984                          337,307,605
1985                          341,226,707
1986                          345,271,125
1987                          349,342,052
1988                          353,477,919
1989                          357,895,891
1990                          362,771,874
1991                          368,224,194
1992                          373,861,907
1993                          379,352,863
1994                          384,587,053
1995                          389,677,579
1996                          394,753,352
1997                          399,925,939
1998                          404,923,356
1999                          409,839,779
2000                          414,651,784
2001                          419,117,923
2002                          423,342,801
2003                          427,424,386
2004                          431,795,881
2005                          436,300,827
2006                          441,042,795
2007                          445,955,481
2008                          451,001,548
2009                          455,905,328
2010                          460,662,636
2011                          465,077,077
2012                          469,572,124
2013                          473,922,844
2014                          478,379,473
2015                          482,763,301
2016                          487,210,962
2017                          491,590,537
dtype: object

In [2]:
import pandas as pd
df_projects=pd.read_csv('projects_data.csv')

/home/ankur/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (44) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [45]:
df_projects.head(2)

,id,regionname,countryname,prodline,lendinginstr,lendinginstrtype,envassesmentcategorycode,supplementprojectflg,productlinetype,projectstatusdisplay,status,project_name,boardapprovaldate,board_approval_month,closingdate,lendprojectcost,ibrdcommamt,idacommamt,totalamt,grantamt,borrower,impagency,url,projectdoc,majorsector_percent,sector1,sector2,sector3,sector4,sector5,sector,mjsector1,mjsector2,mjsector3,mjsector4,mjsector5,mjsector,theme1,theme2,theme3,theme4,theme5,theme,goal,financier,mjtheme1name,mjtheme2name,mjtheme3name,mjtheme4name,mjtheme5name,location,GeoLocID,GeoLocName,Latitude,Longitude,Country,Unnamed: 56
0,P162228,Other,World;World,RE,Investment Project Financing,IN,C,N,L,Active,Active,Creating a Trade in Value-Added Database for ...,2018-06-28T00:00:00Z,June,NaN,"500,000",0,0,0,"500,000",NaN,NaN,http://projects.worldbank.org/P162228?lang=en,nan,nan,!$!0,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,NaN,!$!0,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,nan,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,nan
1,P163962,Africa,Democratic Republic of the Congo;Democratic Re...,PE,Investment Project Financing,IN,B,N,L,Active,Active,Productive Inclusion Project,2018-06-28T00:00:00Z,June,2023-12-31T00:00:00Z,"200,000,000",0,"200,000,000","200,000,000",0,NaN,NaN,http://projects.worldbank.org/P163962?lang=en,nan,nan,!$!0,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,NaN,!$!0,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,nan,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,nan

In [46]:
df_projects.drop(['Unnamed: 56'], axis=1, inplace=True)

In [47]:
df_projects.dtypes

id                           object
regionname                   object
countryname                  object
prodline                     object
lendinginstr                 object
lendinginstrtype             object
envassesmentcategorycode     object
supplementprojectflg         object
productlinetype              object
projectstatusdisplay         object
status                       object
project_name                 object
boardapprovaldate            object
board_approval_month         object
closingdate                  object
lendprojectcost              object
ibrdcommamt                  object
idacommamt                   object
totalamt                     object
grantamt                     object
borrower                     object
impagency                    object
url                          object
projectdoc                  float64
majorsector_percent         float64
sector1                      object
sector2                      object
sector3                      object
sector4                      object
sector5                      object
sector                       object
mjsector1                   float64
mjsector2                   float64
mjsector3                   float64
mjsector4                   float64
mjsector5                   float64
mjsector                     object
theme1                       object
theme2                       object
theme3                       object
theme4                       object
theme5                       object
theme                       float64
goal                         object
financier                    object
mjtheme1name                float64
mjtheme2name                float64
mjtheme3name                float64
mjtheme4name                float64
mjtheme5name                float64
location                     object
GeoLocID                     object
GeoLocName                   object
Latitude                     object
Longitude                    object
Country                      object
dtype: object

In [48]:
df_projects[['totalamt','lendprojectcost']].head(5)

      totalamt lendprojectcost
0            0         500,000
1  200,000,000     200,000,000
2   58,330,000      50,000,000
3   20,000,000      50,000,000
4  100,000,000     100,000,000

In [6]:
df_projects['totalamt']=pd.to_numeric(df_projects['totalamt'].str.replace(',',''))

In [4]:
df_projects['lendprojectcost']=pd.to_numeric(df_projects['lendprojectcost'].str.replace(',',''))

In [7]:
df_projects[['totalamt','lendprojectcost']].dtypes

totalamt             int64
lendprojectcost    float64
dtype: object

## imputing data

In [8]:
import pandas as pd
df_impute = pd.read_csv('gdp_data.csv', skiprows=4)
df_impute.drop('Unnamed: 62', axis=1, inplace=True)

In [9]:
df_impute.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.791961e+09,2.498933e+09,2.467704e+09,2.584464e+09,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,...,1.019053e+10,1.248694e+10,1.593680e+10,1.793024e+10,2.053654e+10,2.026425e+10,2.061610e+10,1.921556e+10,1.946902e+10,2.081530e+10
2,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.417804e+10,7.549239e+10,8.252614e+10,1.041158e+11,1.139232e+11,1.249125e+11,1.267302e+11,1.026212e+11,9.533720e+10,1.242094e+11
3,Albania,ALB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.288135e+10,1.204421e+10,1.192695e+10,1.289087e+10,1.231978e+10,1.277628e+10,1.322824e+10,1.138693e+10,1.188368e+10,1.303935e+10
4,Andorra,AND,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.007353e+09,3.660531e+09,3.355695e+09,3.442063e+09,3.164615e+09,3.281585e+09,3.350736e+09,2.811489e+09,2.877312e+09,3.012914e+09

In [10]:
df_impute.shape

(264, 62)

In [15]:
df_impute.isnull().sum()

Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960              140
1961              140
1962              139
1963              139
1964              139
1965              128
1966              127
1967              123
1968              119
1969              119
1970              111
1971              109
1972              109
1973              109
1974              108
1975              104
1976              103
1977               99
1978              100
1979               99
1980               87
1981               83
1982               77
1983               76
1984               74
1985               72
                 ...
1988               64
1989               60
1990               44
1991               50
1992               47
1993               42
1994               37
1995               28
1996               27
1997               28
1998               26
1999               25
2000               19
2001               19
2002               15
2003               15
2004               14
2005               14
2006               13
2007               13
2008               15
2009               15
2010               15
2011               14
2012               17
2013               16
2014               17
2015               18
2016               23
2017               30
Length: 62, dtype: int64

In [16]:
# put the data set into long form instead of wide
df_melt=pd.melt(df_impute, id_vars=['Country Name','Country Code','Indicator Name','Indicator Code'],
               var_name='year', value_name='GDP')

In [17]:
df_melt.head()

,Country Name,Country Code,Indicator Name,Indicator Code,year,GDP
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,1960,NaN
1,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,1960,5.377778e+08
2,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,1960,NaN
3,Albania,ALB,GDP (current US$),NY.GDP.MKTP.CD,1960,NaN
4,Andorra,AND,GDP (current US$),NY.GDP.MKTP.CD,1960,NaN

In [19]:
df_melt.dtypes

Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
year               object
GDP               float64
dtype: object

In [23]:
df_melt['year']=pd.to_datetime(df_melt['year'])

In [24]:
df_melt.dtypes

Country Name              object
Country Code              object
Indicator Name            object
Indicator Code            object
year              datetime64[ns]
GDP                      float64
dtype: object

In [25]:
df_melt.fillna(method='ffill')

,Country Name,Country Code,Indicator Name,Indicator Code,year,GDP
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,NaN
1,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,5.377778e+08
2,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,5.377778e+08
3,Albania,ALB,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,5.377778e+08
4,Andorra,AND,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,5.377778e+08
5,Arab World,ARB,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,5.377778e+08
6,United Arab Emirates,ARE,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,5.377778e+08
7,Argentina,ARG,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,5.377778e+08
8,Armenia,ARM,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,5.377778e+08
9,American Samoa,ASM,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,5.377778e+08
10,Antigua and Barbuda,ATG,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,5.377778e+08
11,Australia,AUS,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,1.857319e+10
12,Austria,AUT,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,6.592694e+09
13,Azerbaijan,AZE,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,6.592694e+09
14,Burundi,BDI,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,1.960000e+08
15,Belgium,BEL,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,1.165872e+10
16,Benin,BEN,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,2.261956e+08
17,Burkina Faso,BFA,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,3.304428e+08
18,Bangladesh,BGD,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,4.274894e+09
19,Bulgaria,BGR,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,4.274894e+09
20,Bahrain,BHR,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,4.274894e+09
21,"Bahamas, The",BHS,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,1.698039e+08
22,Bosnia and Herzegovina,BIH,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,1.698039e+08
23,Belarus,BLR,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,1.698039e+08
24,Belize,BLZ,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,2.807189e+07
25,Bermuda,BMU,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,8.446665e+07
26,Bolivia,BOL,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,5.631101e+08
27,Brazil,BRA,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,5.631101e+08
28,Barbados,BRB,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,5.631101e+08
29,Brunei Darussalam,BRN,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,5.631101e+08
...,...,...,...,...,...,...
15282,Latin America & the Caribbean (IDA & IBRD coun...,TLA,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,5.704713e+12
15283,Timor-Leste,TLS,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,2.954621e+09
15284,Middle East & North Africa (IDA & IBRD countries),TMN,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,1.417010e+12
15285,Tonga,TON,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,4.260575e+08
15286,South Asia (IDA & IBRD),TSA,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,3.291738e+12
15287,Sub-Saharan Africa (IDA & IBRD countries),TSS,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,1.648714e+12
15288,Trinidad and Tobago,TTO,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,2.210478e+10
15289,Tunisia,TUN,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,4.025668e+10
15290,Turkey,TUR,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,8.511024e+11
15291,Tuvalu,TUV,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,3.973132e+07
15292,Tanzania,TZA,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,5.209032e+10
15293,Uganda,UGA,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,2.589106e+10
15294,Ukraine,UKR,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,1.121542e+11
15295,Upper middle income,UMC,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,2.216842e+13
15296,Uruguay,URY,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,5.615697e+10
15297,United States,USA,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,1.939060e+13
15298,Uzbekistan,UZB,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,4.871769e+10
15299,St. Vincent and the Grenadines,VCT,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,7.896296e+08
15300,"Venezuela, RB",VEN,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,7.896296e+08
15301,British Virgin Islands,VGB,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,7.896296e+08
15302,Virgin Islands (U.S.),VIR,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,7.896296e+08
15303,Vietnam,VNM,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,2.238640e+11
15304,Vanuatu,VUT,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,8.628798e+08
15305,World,WLD,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,8.068379e+13
15306,Samoa,WSM,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,8.566265e+08
15307,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,7.128691e+09
15308,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,7.128691e+09
15309,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,3.494193e+11
15310,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,2.580867e+10
15311,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,2017-01-01,1.784582e+10

In [26]:
df_melt.head()

,Country Name,Country Code,Indicator Name,Indicator Code,year,GDP
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,NaN
1,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,5.377778e+08
2,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,NaN
3,Albania,ALB,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,NaN
4,Andorra,AND,GDP (current US$),NY.GDP.MKTP.CD,1960-01-01,NaN

## Connection to Sqlite

In [30]:
import sqlite3
import pandas as pd

# connect to the database
conn=sqlite3.connect('population_data.db')

# run a query
pd.read_sql('select * from POPULATION_DATA', conn)

,index,Country_Name,Country_Code,Indicator_Name,Indicator_Code,1960,1961,1962,1963,1964,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,0,Aruba,ABW,"Population, total",SP.POP.TOTL,5.421100e+04,5.543800e+04,5.622500e+04,5.669500e+04,5.703200e+04,...,1.013530e+05,1.014530e+05,1.016690e+05,1.020530e+05,1.025770e+05,1.031870e+05,1.037950e+05,1.043410e+05,1.048220e+05,1.052640e+05
1,1,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8.996351e+06,9.166764e+06,9.345868e+06,9.533954e+06,9.731361e+06,...,2.729403e+07,2.800433e+07,2.880317e+07,2.970860e+07,3.069696e+07,3.173169e+07,3.275802e+07,3.373649e+07,3.465603e+07,3.553008e+07
2,2,Angola,AGO,"Population, total",SP.POP.TOTL,5.643182e+06,5.753024e+06,5.866061e+06,5.980417e+06,6.093321e+06,...,2.175942e+07,2.254955e+07,2.336913e+07,2.421856e+07,2.509615e+07,2.599834e+07,2.692047e+07,2.785930e+07,2.881346e+07,2.978419e+07
3,3,Albania,ALB,"Population, total",SP.POP.TOTL,1.608800e+06,1.659800e+06,1.711319e+06,1.762621e+06,1.814135e+06,...,2.947314e+06,2.927519e+06,2.913021e+06,2.905195e+06,2.900401e+06,2.895092e+06,2.889104e+06,2.880703e+06,2.876101e+06,2.873457e+06
4,4,Andorra,AND,"Population, total",SP.POP.TOTL,1.341100e+04,1.437500e+04,1.537000e+04,1.641200e+04,1.746900e+04,...,8.386100e+04,8.446200e+04,8.444900e+04,8.375100e+04,8.243100e+04,8.078800e+04,7.922300e+04,7.801400e+04,7.728100e+04,7.696500e+04
5,5,Arab World,ARB,"Population, total",SP.POP.TOTL,9.249093e+07,9.504450e+07,9.768229e+07,1.004111e+08,1.032399e+08,...,3.398255e+08,3.481451e+08,3.565089e+08,3.648959e+08,3.733070e+08,3.817021e+08,3.900430e+08,3.983050e+08,4.064527e+08,4.144919e+08
6,6,United Arab Emirates,ARE,"Population, total",SP.POP.TOTL,9.263400e+04,1.010780e+05,1.124720e+05,1.255660e+05,1.385290e+05,...,6.894278e+06,7.666393e+06,8.270684e+06,8.672475e+06,8.900453e+06,9.006263e+06,9.070867e+06,9.154302e+06,9.269612e+06,9.400145e+06
7,7,Argentina,ARG,"Population, total",SP.POP.TOTL,2.061908e+07,2.095308e+07,2.128768e+07,2.162184e+07,2.195393e+07,...,4.038239e+07,4.079941e+07,4.122389e+07,4.165688e+07,4.209674e+07,4.253992e+07,4.298152e+07,4.341776e+07,4.384743e+07,4.427104e+07
8,8,Armenia,ARM,"Population, total",SP.POP.TOTL,1.874120e+06,1.941491e+06,2.009526e+06,2.077575e+06,2.144998e+06,...,2.908220e+06,2.888584e+06,2.877311e+06,2.875581e+06,2.881922e+06,2.893509e+06,2.906220e+06,2.916950e+06,2.924816e+06,2.930450e+06
9,9,American Samoa,ASM,"Population, total",SP.POP.TOTL,2.001300e+04,2.048600e+04,2.111700e+04,2.188200e+04,2.269800e+04,...,5.703000e+04,5.622700e+04,5.563700e+04,5.532000e+04,5.523000e+04,5.530700e+04,5.543700e+04,5.553700e+04,5.559900e+04,5.564100e+04
10,10,Antigua and Barbuda,ATG,"Population, total",SP.POP.TOTL,5.533900e+04,5.614400e+04,5.714400e+04,5.829400e+04,5.952400e+04,...,9.247800e+04,9.358100e+04,9.466100e+04,9.571900e+04,9.677700e+04,9.782400e+04,9.887500e+04,9.992300e+04,1.009630e+05,1.020120e+05
11,11,Australia,AUS,"Population, total",SP.POP.TOTL,1.027648e+07,1.048300e+07,1.074200e+07,1.095000e+07,1.116700e+07,...,2.124920e+07,2.169170e+07,2.203175e+07,2.234002e+07,2.274248e+07,2.314590e+07,2.350414e+07,2.385078e+07,2.421081e+07,2.459893e+07
12,12,Austria,AUT,"Population, total",SP.POP.TOTL,7.047539e+06,7.086299e+06,7.129864e+06,7.175811e+06,7.223801e+06,...,8.321496e+06,8.343323e+06,8.363404e+06,8.391643e+06,8.429991e+06,8.479823e+06,8.546356e+06,8.642699e+06,8.736668e+06,8.809212e+06
13,13,Azerbaijan,AZE,"Population, total",SP.POP.TOTL,3.895396e+06,4.030320e+06,4.171425e+06,4.315128e+06,4.456689e+06,...,8.763400e+06,8.947243e+06,9.054332e+06,9.173082e+06,9.295784e+06,9.416801e+06,9.535079e+06,9.649341e+06,9.757812e+06,9.862429e+06
14,14,Burundi,BDI,"Population, total",SP.POP.TOTL,2.786106e+06,2.839666e+06,2.893669e+06,2.949926e+06,3.010859e+06,...,8.212264e+06,8.489031e+06,8.766930e+06,9.043508e+06,9.319710e+06,9.600186e+06,9.891790e+06,1.019927e+07,1.052412e+07,1.086424e+07
15,15,Belgium,BEL,"Population, total",SP.POP.TOTL,9.153489e+06,9.183948e+06,9.220578e+06,9.289770e+06,9.378113e+06,...,1.070997e+07,1.079649e+07,1.089559e+07,1.104774e+07,1.112825e+07,1.118282e+07,1.120906e+07,1.127420e+07,1.133142e+07,1.137207e+07
16,16,Benin,BEN,"Population, total",SP.POP.TOTL,2.431622e+06,2.465867e+06,2.502896e+06,2.542859e+06,2.585965e+06,...,8.696916e+06,8.944706e+06,9.199259e+06,9.460802e+06,9.729160e+06,1.000445e+07,1.028671e+07,1.057595e+07,1.087230e+07,1.117569e+07
17,17,Burkina Faso,BFA,"Population, total",SP.POP.TOTL,4.829288e+06,4.894580e+06,4.960326e+06,5.027821e+06,5.098890e+06,...,1.468973e+07,1.514110e+07,1.560522e+07,1.608190e+07,1.657122e+07,1.707272e+07,1.758598e+07,1.811062e+07,1.864643e+07,1.919338e+07
18,18,Bangladesh,BGD,"Population, total",SP.POP.TOTL,4.819975e+07,4.959280e+07,5.103014e+07,5.253242e+07,5.412910e+07,...,1.488058e+08,1.504547e+08,1.521491e+08,1.539119e+08,1.557271e+08,1.575713e+08,1.594053e+08,1.612009e+08,1.629516e+08,1.646698e+08
19,19,Bulgaria,BGR,"Population, total",SP.POP.TOTL,7.867374e+06,7.943118e+06,8.012946e+06,8.078145e+06,8.144340e+06,...,7.492561e+06,7.444443e+06,7.395599e+06,7.348328e+06,7.305888e+06,7.265115e+06,7.223938e+06,7.177991e+06,7.127822e+06,7.075991e+06
20,20,Bahrain,BHR,"Population, total",SP.POP.TOTL,1.624270e+05,1.678940e+05,1.731440e+05,1.781400e+05,1.828870e+05,...,1.114590e+06,1.185029e+06,1.240862e+06,1.278269e+06,1.300217e+06,1.315411e+06,1.336397e+06,1.371855e+06,1.425171e+06,1.492584e+06
21,21,"Bahamas, The",BHS,"Population, total",SP.POP.TOTL,1.095280e+05,1.151080e+05,1.210830e+05,1.273330e+05,1.336980e+05,...,3.486760e+05,3.548560e+05,3.608320e+05,3.665680e+05,3.720390e+05,3.772400e+05,3.821690e+05,3.868380e+05,3.912320e+05,3.953610e+05
22,22,Bosnia and Herzegovina,BIH,"Population, total",SP.POP.TOTL,3.225668e+06,3.288602e+06,3.353226e+06,3.417574e+06,3.478995e+06,...,3.763599e+06,3.746561e+06,3.722084e+06,3.688865e+06,3.648200e+06,3.604999e+06,3.566002e+06,3.535961e+06,3.516816e+06,3.507017e+06
23,23,Belarus,BLR,"Population, total",SP.POP.TOTL,8.198000e+06,8.271216e+06,8.351928e+06,8.437232e+06,8.524224e+06,...,9.527985e+06,9.506765e+06,9.490583e+06,9.473172e+06,9.464495e+06,9.465997e+06,9.474511e+06,9.489616e+06,9.501534e+06,9.507875e+06
24,24,Belize,BLZ,"Population, total",SP.POP.TOTL,9.206400e+04,9.470300e+04,9.738400e+04,1.001640e+05,1.030690e+05,...,3.061650e+05,3.139290e+05,3.216080e+05,3.291920e+05,3.367010e+05,3.441810e+05,3.516940e+05,3.592880e+05,3.669540e+05,3.746810e+05
25,25,Bermuda,BMU,"Population, total",SP.POP.TOTL,4.440000e+04,4.550000e+04,4.660000e+04,4.770000e+04,4.890000e+04,...,6.527300e+04,6.563600e+04,6.512400e+04,6.456400e+04,6.479800e+04,6.500100e+04,6.513900e+04,6.523900e+04,6.534100e+04,6.544100e+04
26,26,Bolivia,BOL,"Population, total",SP.POP.TOTL,3.693449e+06,3.764813e+06,3.838097e+06,3.913395e+06,3.990857e+06,...,9.599855e+06,9.758748e+06,9.918242e+06,1.007834e+07,1.023900e+07,1.040026e+07,1.056216e+07,1.072470e+07,1.088788e+07,1.105160e+07
27,27,Brazil,BRA,"Population, total",SP.POP.TOTL,7.220755e+07,7.435176e+07,7.657325e+07,7.885402e+07,8.116865e+07,...,1.929790e+08,1.948960e+08,1.967963e+08,1.986867e+08,2.005610e+08,2.024086e+08,2.042131e+08,2.059621e+08,2.076529e+08,2.092883e+08
28,28,Barbados,BRB,"Population, total",SP.POP.TOTL,2.309390e+05,2.316780e+05,2.325860e+05,2.335870e+05,2.345470e+05,...,2.773190e+05,2.784700e+05,2.795690e+05,2.806010e+05,2.815850e+05,2.825090e+05,2.833850e+05,2.842170e+05,2.849960e+05,2.857190e+05
29,29,Brunei Darussalam,BRN,"Population, total",SP.POP.TOTL,8.174500e+04,8.559600e+04,8.951600e+04,9.357600e+04,9.784800e+04,...,3.792520e+05,3.837720e+05,3.886620e+05,3.940130e+05,3.997480e+05,4.057160e+05,4.117040e+05,4.175420e+05,4.231960e+05,4.286970e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,"Population, total",SP.POP.TOTL,2.103576e+08,2.162859e+08,2.223965e+08,2.286630e+08,2.350485e+08,...,5.659562e+08,5.731253e+08,5.802468e+08,5.873151e+08,5.943307e+08,6.012772e+08,6.081360e+08,6.148920e+08,6.215349e+08,6.280598e+08
235,235,Timor-Leste,TLS,"Population, total",SP.POP.TOTL,4.999500e+05,5.088450e+05,5.181070e+05,5.277490e+05,5.377860e+05,...,1.078110e+06,1.092021e+06,1.109591e+06,1.131523e+06,1.156760e+06,1.184366e+06,1.212814e+06,1.240977e+06,1.268671e+06,1.296311e+06
236,236,Middle East & North Africa (IDA & IBRD countries),TMN,"Population, total",SP.POP.TOTL,9.783777e+07,1.004585e+08,1.031472e+08,1.059144e+08,1.087749e+08,...,3.199345e+08,3.257867e+08,3.317705e+08,3.378950e+08,3.441488e+08,3.504715e+08,3.567833e+08,3.630272e+08,3.691675e+08,3.752170e+08
237,237,Tonga,TON,"Population, total",SP.POP.TOTL,6.160100e+04,6.374500e+04,6.625900e+04,6.900500e+04,7.175700e+04,...,1.030050e+05,1.036040e+05,1.041370e+05,1.045770e+05,1.049510e+05,1.053280e+05,1.057820e+05,1.063640e+05,1.071220e+05,1.080200e+05
238,238,South Asia (IDA & IBRD),TSA,"Population, total",SP.POP.TOTL,5.718357e+08,5.838941e+08,5.964139e+08,6.093918e+08,6.228226e+08,...,1.584359e+09,1.607664e+09,1.630807e+09,1.653799e+09,1.676615e+09,1.699310e+09,1.721848e+09,1.744200e+09,1.766394e+09,1.788389e+09
239,239,Sub-Saharan Africa (IDA & IBRD countries),TSS,"Population, total",SP.POP.TOTL,2.285860e+08,2.340086e+08,2.396471e+08,2.455033e+08,2.515764e+08,...,8.309656e+08,8.539537e+08,8.776284e+08,9.019899e+08,9.270399e+08,9.527341e+08,9.790179e+08,1.005850e+09,1.033213e+09,1.061108e+09
240,240,Trinidad and Tobago,TTO,"Population, total",SP.POP.TOTL,8.484790e+05,8.653600e+05,8.800230e+05,8.925690e+05,9.032750e+05,...,1.315372e+06,1.321618e+06,1.328100e+06,1.334788e+06,1.341588e+06,1.348248e+06,1.354493e+06,1.360092e+06,1.364962e+06,1.369125e+06
241,241,Tunisia,TUN,"Population, total",SP.POP.TOTL,4.176266e+06,4.235937e+06,4.303131e+06,4.377637e+06,4.458611e+06,...,1.040734e+07,1.052183e+07,1.063993e+07,1.076147e+07,1.088667e+07,1.101456e+07,1.114391e+07,1.127366e+07,1.140325e+07,1.153213e+07
242,242,Turkey,TUR,"Population, total",SP.POP.TOTL,2.747233e+07,2.814689e+07,2.883280e+07,2.953134e+07,3.024423e+07,...,7.044003e+07,7.133918e+07,7.232691e+07,7.340946e+07,7.456987e+07,7.578733e+07,7.703063e+07,7.827147e+07,7.951243e+07,8.074502e+07
243,243,Tuvalu,TUV,"Population, total",SP.POP.TOTL,6.104000e+03,6.246000e+03,6.389000e+03,6.538000e+03,6.684000e+03,...,1.034000e+04,1.044100e+04,1.053100e+04,1.062800e+04,1.072500e+04,1.081900e+04,1.090800e+04,1.100100e+04,1.109700e+04,1.119200e+04
244,244,Tanzania,TZA,"Population, total",SP.POP.TOTL,1.007451e+07,1.037340e+07,1.068391e+07,1.100590e+07,1.133910e+07,...,4.327014e+07,4.466423e+07,4.609859e+07,4.757090e+07,4.908300e+07,5.063660e+07,5.223487e+07,5.387996e+07,5.557220e+07,5.731002e+07
245,245,Uganda,UGA,"Population, total",SP.POP.TOTL,6.788214e+06,7.006633e+06,7.240174e+06,7.487429e+06,7.746198e+06,...,3.166390e+07,3.277190e+07,3.391513e+07,3.509365e+07,3.630680e+07,3.755373e+07,3.883334e+07,4.014487e+07,4.148796e+07,4.286296e+07
246,246,Ukraine,UKR,"Population, total",SP.POP.TOTL,4.266215e+07,4.320364e+07,4.374947e+07,4.428590e+07,4.479433e+07,...,4.625820e+07,4.605330e+07,4.587070e+07,4.570610e+07,4.559330e+07,4.548960e+07,4.527195e+07,4.515403e+07,4.500464e+07,4.483116e+07
247,247,Upper middle income,UMC,"Population, total",SP.POP.TOTL,1.150569e+09,1.154967e+09,1.171821e+09,1.200060e+09,1.227974e+09,...,2.404283e+09,2.422394e+09,2.440543e+09,2.459176e+09,2.478492e+09,2.498184e+09,2.517980e+09,2.537437e+09,2.556922e+09,2.576203e+09
248,248,Uruguay,URY,"Population, total",SP.POP.TOTL,2.538651e+06,2.571690e+06,2.603887e+06,2.635129e+06,2.665390e+06,...,3.350824e+06,3.362755e+06,3.374415e+06,3.385624e+06,3.396777e+06,3.408005e+06,3.419546e+06,3.431552e+06,3.444006e+06,3.456750e+06
249,249,United States,USA,"Population, total",SP.POP.TOTL,1.806710e+08,1.836910e+08,1.865380e+08,1.892420e+08,1.918890e+08,...,3.040940e+08,3.067715e+08,3.093384e+08,3.116443e+08,3.139933e+08,3.162345e+08,3.186225e+08,3.210398e+08,3.234059e+08,3.257192e+08
250,250,Uzbekistan,UZB,"Population, total",SP.POP.TOTL,8.549493e+06,8.837349e+06,9.138097e+06,9.454250e+06,9.788986e+06,...,2.730280e+07,2.776740e+07,2.856240e+07,2.933940e+07,2.977450e+07,3.024320e+07,3.075770e+07,3.129890e+07,3.184790e+07,3.238720e+07
251,251,St. Vincent and the Grenadines,VCT,"Population, total",SP.POP.TOTL,8.094900e+04,8.214200e+04,8.320600e+04,8.416700e+04,8.506900e+04,...,1.091650e+05,1.092530e+05,1.093150e+05,1.093410e+05,1.093280e+05,1.093200e+05,1.093570e+05,1.094550e+05,1.096430e+05,1.098970e+05
252,252,"Venezuela, RB",VEN,"Population, total",SP.POP.TOTL,8.146847e+06,8.461685e+06,8.790589e+06,9.130349e+06,9.476252e+06,...,2.814170e+07,2.858732e+07,2.902803e+07,2.946329e+07,2.989308e+07,3.031785e+07,3.073838e+07,3.115513e+07,3.156818e+07,3.197706e+07
253,253,British Virgin Islands,VGB,"Population, total",SP.POP.TOTL,8.033000e+03,8.155000e+03,8.298000e+03,8.452000e+03,8.627000e+03,...,2.560400e+04,2.644700e+04,2.722400e+04,2.790100e+04,2.850900e+04,2.905600e+04,2.958800e+04,3.011300e+04,3.066100e+04,3.119600e+04
254,254,Virgin Islands (U.S.),VIR,"Population, total",SP.POP.TOTL,3.250000e+04,3.430000e+04,3.500000e+04,3.980000e+04,4.080000e+04,...,1.083990e+05,1.084050e+05,1.083580e+05,1.082920e+05,1.081910e+05,1.080440e+05,1.078840e+05,1.077100e+05,1.075100e+05,1.072680e+05
255,255,Vietnam,VNM,"Population, total",SP.POP.TOTL,3.267063e+07,3.366677e+07,3.468416e+07,3.572209e+07,3.678098e+07,...,8.670780e+07,8.756541e+07,8.847251e+07,8.943664e+07,9.045188e+07,9.149772e+07,9.254492e+07,9.357157e+07,9.456907e+07,9.554080e+07
256,256,Vanuatu,VUT,"Population, total",SP.POP.TOTL,6.369900e+04,6.571300e+04,6.780800e+04,6.996400e+04,7.213100e+04,...,2.253400e+05,2.307850e+05,2.362950e+05,2.418710e+05,2.474850e+05,2.531420e+05,2.588500e+05,2.646030e+05,2.704020e+05,2.762440e+05
257,257,World,WLD,"Population, total",SP.POP.TOTL,3.032160e+09,3.073369e+09,3.126510e+09,3.191786e+09,3.257460e+09,...,6.766297e+09,6.849569e+09,6.932870e+09,7.014984e+09,7.099558e+09,7.185138e+09,7.271323e+09,7.357559e+09,7.444157e+09,7.530360e+09
258,258,Samoa,WSM,"Population, total",SP.POP.TOTL,1.086460e+05,1.121190e+05,1.157880e+05,1.195610e+05,1.233540e+05,...,1.835260e+05,1.848260e+05,1.862050e+05,1.876650e+05,1.891940e+05,1.907570e+05,1.922900e+05,1.937590e+05,1.951250e+05,1.964400e+05
259,259,Kosovo,XKX,"Population, total",SP.POP.TOTL,9.470000e+05,9.660000e+05,9.940000e+05,1.022000e+06,1.050000e+06,...,1.747383e+06,1.761474e+06,1.775680e+06,1.791000e+06,1.805200e+06,1.824100e+06,1.821800e+06,1.801800e+06,1.816200e+06,1.830700e+06
260,260,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5.172135e+06,5.260501e+06,5.351799e+06,5.446063e+06,5.543339e+06,...,2.235639e+07,2.297493e+07,2.360678e+07,2.425221e+07,2.490997e+07,2.557632e+07,2.624633e+07,2.691621e+07,2.758421e+07,2.825042e+07
261,261,South Africa,ZAF,"Population, total",SP.POP.TOTL,1.745686e+07,1.792067e+07,1.840161e+07,1.889928e+07,1.941298e+07,...,5.041213e+07,5.097082e+07,5.158466e+07,5.226352e+07,5.299821e+07,5.376740e+07,5.453957e+07,5.529122e+07,5.601547e+07,5.671716e+07
262,262,Zambia,ZMB,"Population, total",SP.POP.TOTL,3.044846e+06,3.140264e+06,3.240587e+06,3.345145e+06,3.452942e+06,...,1.308252e+07,1.345642e+07,1.385003e+07,1.426476e+07,1.469994e+07,1.515321e+07,1.562097e+07,1.610059e+07,1.659139e+07,1.709413e+07
263,263,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3.747369e+06,3.870756e+06,3.999419e+06,4.132756e+06,4.269863e+06,...,1.355847e+07,1.381060e+07,1.408632e+07,1.438665e+07,1.471083e+07,1.505451e+07,1.541168e+07,1.577745e+07,1.615036e+07,1.652990e+07

## Connection to Mysql or Postgresql

In [32]:
import pandas as pd
from sqlalchemy import create_engine

engine= create_engine('sqlite:///population_data.db')
pd.read_sql("SELECT * FROM population_data", engine)

,index,Country_Name,Country_Code,Indicator_Name,Indicator_Code,1960,1961,1962,1963,1964,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,0,Aruba,ABW,"Population, total",SP.POP.TOTL,5.421100e+04,5.543800e+04,5.622500e+04,5.669500e+04,5.703200e+04,...,1.013530e+05,1.014530e+05,1.016690e+05,1.020530e+05,1.025770e+05,1.031870e+05,1.037950e+05,1.043410e+05,1.048220e+05,1.052640e+05
1,1,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8.996351e+06,9.166764e+06,9.345868e+06,9.533954e+06,9.731361e+06,...,2.729403e+07,2.800433e+07,2.880317e+07,2.970860e+07,3.069696e+07,3.173169e+07,3.275802e+07,3.373649e+07,3.465603e+07,3.553008e+07
2,2,Angola,AGO,"Population, total",SP.POP.TOTL,5.643182e+06,5.753024e+06,5.866061e+06,5.980417e+06,6.093321e+06,...,2.175942e+07,2.254955e+07,2.336913e+07,2.421856e+07,2.509615e+07,2.599834e+07,2.692047e+07,2.785930e+07,2.881346e+07,2.978419e+07
3,3,Albania,ALB,"Population, total",SP.POP.TOTL,1.608800e+06,1.659800e+06,1.711319e+06,1.762621e+06,1.814135e+06,...,2.947314e+06,2.927519e+06,2.913021e+06,2.905195e+06,2.900401e+06,2.895092e+06,2.889104e+06,2.880703e+06,2.876101e+06,2.873457e+06
4,4,Andorra,AND,"Population, total",SP.POP.TOTL,1.341100e+04,1.437500e+04,1.537000e+04,1.641200e+04,1.746900e+04,...,8.386100e+04,8.446200e+04,8.444900e+04,8.375100e+04,8.243100e+04,8.078800e+04,7.922300e+04,7.801400e+04,7.728100e+04,7.696500e+04
5,5,Arab World,ARB,"Population, total",SP.POP.TOTL,9.249093e+07,9.504450e+07,9.768229e+07,1.004111e+08,1.032399e+08,...,3.398255e+08,3.481451e+08,3.565089e+08,3.648959e+08,3.733070e+08,3.817021e+08,3.900430e+08,3.983050e+08,4.064527e+08,4.144919e+08
6,6,United Arab Emirates,ARE,"Population, total",SP.POP.TOTL,9.263400e+04,1.010780e+05,1.124720e+05,1.255660e+05,1.385290e+05,...,6.894278e+06,7.666393e+06,8.270684e+06,8.672475e+06,8.900453e+06,9.006263e+06,9.070867e+06,9.154302e+06,9.269612e+06,9.400145e+06
7,7,Argentina,ARG,"Population, total",SP.POP.TOTL,2.061908e+07,2.095308e+07,2.128768e+07,2.162184e+07,2.195393e+07,...,4.038239e+07,4.079941e+07,4.122389e+07,4.165688e+07,4.209674e+07,4.253992e+07,4.298152e+07,4.341776e+07,4.384743e+07,4.427104e+07
8,8,Armenia,ARM,"Population, total",SP.POP.TOTL,1.874120e+06,1.941491e+06,2.009526e+06,2.077575e+06,2.144998e+06,...,2.908220e+06,2.888584e+06,2.877311e+06,2.875581e+06,2.881922e+06,2.893509e+06,2.906220e+06,2.916950e+06,2.924816e+06,2.930450e+06
9,9,American Samoa,ASM,"Population, total",SP.POP.TOTL,2.001300e+04,2.048600e+04,2.111700e+04,2.188200e+04,2.269800e+04,...,5.703000e+04,5.622700e+04,5.563700e+04,5.532000e+04,5.523000e+04,5.530700e+04,5.543700e+04,5.553700e+04,5.559900e+04,5.564100e+04
10,10,Antigua and Barbuda,ATG,"Population, total",SP.POP.TOTL,5.533900e+04,5.614400e+04,5.714400e+04,5.829400e+04,5.952400e+04,...,9.247800e+04,9.358100e+04,9.466100e+04,9.571900e+04,9.677700e+04,9.782400e+04,9.887500e+04,9.992300e+04,1.009630e+05,1.020120e+05
11,11,Australia,AUS,"Population, total",SP.POP.TOTL,1.027648e+07,1.048300e+07,1.074200e+07,1.095000e+07,1.116700e+07,...,2.124920e+07,2.169170e+07,2.203175e+07,2.234002e+07,2.274248e+07,2.314590e+07,2.350414e+07,2.385078e+07,2.421081e+07,2.459893e+07
12,12,Austria,AUT,"Population, total",SP.POP.TOTL,7.047539e+06,7.086299e+06,7.129864e+06,7.175811e+06,7.223801e+06,...,8.321496e+06,8.343323e+06,8.363404e+06,8.391643e+06,8.429991e+06,8.479823e+06,8.546356e+06,8.642699e+06,8.736668e+06,8.809212e+06
13,13,Azerbaijan,AZE,"Population, total",SP.POP.TOTL,3.895396e+06,4.030320e+06,4.171425e+06,4.315128e+06,4.456689e+06,...,8.763400e+06,8.947243e+06,9.054332e+06,9.173082e+06,9.295784e+06,9.416801e+06,9.535079e+06,9.649341e+06,9.757812e+06,9.862429e+06
14,14,Burundi,BDI,"Population, total",SP.POP.TOTL,2.786106e+06,2.839666e+06,2.893669e+06,2.949926e+06,3.010859e+06,...,8.212264e+06,8.489031e+06,8.766930e+06,9.043508e+06,9.319710e+06,9.600186e+06,9.891790e+06,1.019927e+07,1.052412e+07,1.086424e+07
15,15,Belgium,BEL,"Population, total",SP.POP.TOTL,9.153489e+06,9.183948e+06,9.220578e+06,9.289770e+06,9.378113e+06,...,1.070997e+07,1.079649e+07,1.089559e+07,1.104774e+07,1.112825e+07,1.118282e+07,1.120906e+07,1.127420e+07,1.133142e+07,1.137207e+07
16,16,Benin,BEN,"Population, total",SP.POP.TOTL,2.431622e+06,2.465867e+06,2.502896e+06,2.542859e+06,2.585965e+06,...,8.696916e+06,8.944706e+06,9.199259e+06,9.460802e+06,9.729160e+06,1.000445e+07,1.028671e+07,1.057595e+07,1.087230e+07,1.117569e+07
17,17,Burkina Faso,BFA,"Population, total",SP.POP.TOTL,4.829288e+06,4.894580e+06,4.960326e+06,5.027821e+06,5.098890e+06,...,1.468973e+07,1.514110e+07,1.560522e+07,1.608190e+07,1.657122e+07,1.707272e+07,1.758598e+07,1.811062e+07,1.864643e+07,1.919338e+07
18,18,Bangladesh,BGD,"Population, total",SP.POP.TOTL,4.819975e+07,4.959280e+07,5.103014e+07,5.253242e+07,5.412910e+07,...,1.488058e+08,1.504547e+08,1.521491e+08,1.539119e+08,1.557271e+08,1.575713e+08,1.594053e+08,1.612009e+08,1.629516e+08,1.646698e+08
19,19,Bulgaria,BGR,"Population, total",SP.POP.TOTL,7.867374e+06,7.943118e+06,8.012946e+06,8.078145e+06,8.144340e+06,...,7.492561e+06,7.444443e+06,7.395599e+06,7.348328e+06,7.305888e+06,7.265115e+06,7.223938e+06,7.177991e+06,7.127822e+06,7.075991e+06
20,20,Bahrain,BHR,"Population, total",SP.POP.TOTL,1.624270e+05,1.678940e+05,1.731440e+05,1.781400e+05,1.828870e+05,...,1.114590e+06,1.185029e+06,1.240862e+06,1.278269e+06,1.300217e+06,1.315411e+06,1.336397e+06,1.371855e+06,1.425171e+06,1.492584e+06
21,21,"Bahamas, The",BHS,"Population, total",SP.POP.TOTL,1.095280e+05,1.151080e+05,1.210830e+05,1.273330e+05,1.336980e+05,...,3.486760e+05,3.548560e+05,3.608320e+05,3.665680e+05,3.720390e+05,3.772400e+05,3.821690e+05,3.868380e+05,3.912320e+05,3.953610e+05
22,22,Bosnia and Herzegovina,BIH,"Population, total",SP.POP.TOTL,3.225668e+06,3.288602e+06,3.353226e+06,3.417574e+06,3.478995e+06,...,3.763599e+06,3.746561e+06,3.722084e+06,3.688865e+06,3.648200e+06,3.604999e+06,3.566002e+06,3.535961e+06,3.516816e+06,3.507017e+06
23,23,Belarus,BLR,"Population, total",SP.POP.TOTL,8.198000e+06,8.271216e+06,8.351928e+06,8.437232e+06,8.524224e+06,...,9.527985e+06,9.506765e+06,9.490583e+06,9.473172e+06,9.464495e+06,9.465997e+06,9.474511e+06,9.489616e+06,9.501534e+06,9.507875e+06
24,24,Belize,BLZ,"Population, total",SP.POP.TOTL,9.206400e+04,9.470300e+04,9.738400e+04,1.001640e+05,1.030690e+05,...,3.061650e+05,3.139290e+05,3.216080e+05,3.291920e+05,3.367010e+05,3.441810e+05,3.516940e+05,3.592880e+05,3.669540e+05,3.746810e+05
25,25,Bermuda,BMU,"Population, total",SP.POP.TOTL,4.440000e+04,4.550000e+04,4.660000e+04,4.770000e+04,4.890000e+04,...,6.527300e+04,6.563600e+04,6.512400e+04,6.456400e+04,6.479800e+04,6.500100e+04,6.513900e+04,6.523900e+04,6.534100e+04,6.544100e+04
26,26,Bolivia,BOL,"Population, total",SP.POP.TOTL,3.693449e+06,3.764813e+06,3.838097e+06,3.913395e+06,3.990857e+06,...,9.599855e+06,9.758748e+06,9.918242e+06,1.007834e+07,1.023900e+07,1.040026e+07,1.056216e+07,1.072470e+07,1.088788e+07,1.105160e+07
27,27,Brazil,BRA,"Population, total",SP.POP.TOTL,7.220755e+07,7.435176e+07,7.657325e+07,7.885402e+07,8.116865e+07,...,1.929790e+08,1.948960e+08,1.967963e+08,1.986867e+08,2.005610e+08,2.024086e+08,2.042131e+08,2.059621e+08,2.076529e+08,2.092883e+08
28,28,Barbados,BRB,"Population, total",SP.POP.TOTL,2.309390e+05,2.316780e+05,2.325860e+05,2.335870e+05,2.345470e+05,...,2.773190e+05,2.784700e+05,2.795690e+05,2.806010e+05,2.815850e+05,2.825090e+05,2.833850e+05,2.842170e+05,2.849960e+05,2.857190e+05
29,29,Brunei Darussalam,BRN,"Population, total",SP.POP.TOTL,8.174500e+04,8.559600e+04,8.951600e+04,9.357600e+04,9.784800e+04,...,3.792520e+05,3.837720e+05,3.886620e+05,3.940130e+05,3.997480e+05,4.057160e+05,4.117040e+05,4.175420e+05,4.231960e+05,4.286970e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,"Population, total",SP.POP.TOTL,2.103576e+08,2.162859e+08,2.223965e+08,2.286630e+08,2.350485e+08,...,5.659562e+08,5.731253e+08,5.802468e+08,5.873151e+08,5.943307e+08,6.012772e+08,6.081360e+08,6.148920e+08,6.215349e+08,6.280598e+08
235,235,Timor-Leste,TLS,"Population, total",SP.POP.TOTL,4.999500e+05,5.088450e+05,5.181070e+05,5.277490e+05,5.377860e+05,...,1.078110e+06,1.092021e+06,1.109591e+06,1.131523e+06,1.156760e+06,1.184366e+06,1.212814e+06,1.240977e+06,1.268671e+06,1.296311e+06
236,236,Middle East & North Africa (IDA & IBRD countries),TMN,"Population, total",SP.POP.TOTL,9.783777e+07,1.004585e+08,1.031472e+08,1.059144e+08,1.087749e+08,...,3.199345e+08,3.257867e+08,3.317705e+08,3.378950e+08,3.441488e+08,3.504715e+08,3.567833e+08,3.630272e+08,3.691675e+08,3.752170e+08
237,237,Tonga,TON,"Population, total",SP.POP.TOTL,6.160100e+04,6.374500e+04,6.625900e+04,6.900500e+04,7.175700e+04,...,1.030050e+05,1.036040e+05,1.041370e+05,1.045770e+05,1.049510e+05,1.053280e+05,1.057820e+05,1.063640e+05,1.071220e+05,1.080200e+05
238,238,South Asia (IDA & IBRD),TSA,"Population, total",SP.POP.TOTL,5.718357e+08,5.838941e+08,5.964139e+08,6.093918e+08,6.228226e+08,...,1.584359e+09,1.607664e+09,1.630807e+09,1.653799e+09,1.676615e+09,1.699310e+09,1.721848e+09,1.744200e+09,1.766394e+09,1.788389e+09
239,239,Sub-Saharan Africa (IDA & IBRD countries),TSS,"Population, total",SP.POP.TOTL,2.285860e+08,2.340086e+08,2.396471e+08,2.455033e+08,2.515764e+08,...,8.309656e+08,8.539537e+08,8.776284e+08,9.019899e+08,9.270399e+08,9.527341e+08,9.790179e+08,1.005850e+09,1.033213e+09,1.061108e+09
240,240,Trinidad and Tobago,TTO,"Population, total",SP.POP.TOTL,8.484790e+05,8.653600e+05,8.800230e+05,8.925690e+05,9.032750e+05,...,1.315372e+06,1.321618e+06,1.328100e+06,1.334788e+06,1.341588e+06,1.348248e+06,1.354493e+06,1.360092e+06,1.364962e+06,1.369125e+06
241,241,Tunisia,TUN,"Population, total",SP.POP.TOTL,4.176266e+06,4.235937e+06,4.303131e+06,4.377637e+06,4.458611e+06,...,1.040734e+07,1.052183e+07,1.063993e+07,1.076147e+07,1.088667e+07,1.101456e+07,1.114391e+07,1.127366e+07,1.140325e+07,1.153213e+07
242,242,Turkey,TUR,"Population, total",SP.POP.TOTL,2.747233e+07,2.814689e+07,2.883280e+07,2.953134e+07,3.024423e+07,...,7.044003e+07,7.133918e+07,7.232691e+07,7.340946e+07,7.456987e+07,7.578733e+07,7.703063e+07,7.827147e+07,7.951243e+07,8.074502e+07
243,243,Tuvalu,TUV,"Population, total",SP.POP.TOTL,6.104000e+03,6.246000e+03,6.389000e+03,6.538000e+03,6.684000e+03,...,1.034000e+04,1.044100e+04,1.053100e+04,1.062800e+04,1.072500e+04,1.081900e+04,1.090800e+04,1.100100e+04,1.109700e+04,1.119200e+04
244,244,Tanzania,TZA,"Population, total",SP.POP.TOTL,1.007451e+07,1.037340e+07,1.068391e+07,1.100590e+07,1.133910e+07,...,4.327014e+07,4.466423e+07,4.609859e+07,4.757090e+07,4.908300e+07,5.063660e+07,5.223487e+07,5.387996e+07,5.557220e+07,5.731002e+07
245,245,Uganda,UGA,"Population, total",SP.POP.TOTL,6.788214e+06,7.006633e+06,7.240174e+06,7.487429e+06,7.746198e+06,...,3.166390e+07,3.277190e+07,3.391513e+07,3.509365e+07,3.630680e+07,3.755373e+07,3.883334e+07,4.014487e+07,4.148796e+07,4.286296e+07
246,246,Ukraine,UKR,"Population, total",SP.POP.TOTL,4.266215e+07,4.320364e+07,4.374947e+07,4.428590e+07,4.479433e+07,...,4.625820e+07,4.605330e+07,4.587070e+07,4.570610e+07,4.559330e+07,4.548960e+07,4.527195e+07,4.515403e+07,4.500464e+07,4.483116e+07
247,247,Upper middle income,UMC,"Population, total",SP.POP.TOTL,1.150569e+09,1.154967e+09,1.171821e+09,1.200060e+09,1.227974e+09,...,2.404283e+09,2.422394e+09,2.440543e+09,2.459176e+09,2.478492e+09,2.498184e+09,2.517980e+09,2.537437e+09,2.556922e+09,2.576203e+09
248,248,Uruguay,URY,"Population, total",SP.POP.TOTL,2.538651e+06,2.571690e+06,2.603887e+06,2.635129e+06,2.665390e+06,...,3.350824e+06,3.362755e+06,3.374415e+06,3.385624e+06,3.396777e+06,3.408005e+06,3.419546e+06,3.431552e+06,3.444006e+06,3.456750e+06
249,249,United States,USA,"Population, total",SP.POP.TOTL,1.806710e+08,1.836910e+08,1.865380e+08,1.892420e+08,1.918890e+08,...,3.040940e+08,3.067715e+08,3.093384e+08,3.116443e+08,3.139933e+08,3.162345e+08,3.186225e+08,3.210398e+08,3.234059e+08,3.257192e+08
250,250,Uzbekistan,UZB,"Population, total",SP.POP.TOTL,8.549493e+06,8.837349e+06,9.138097e+06,9.454250e+06,9.788986e+06,...,2.730280e+07,2.776740e+07,2.856240e+07,2.933940e+07,2.977450e+07,3.024320e+07,3.075770e+07,3.129890e+07,3.184790e+07,3.238720e+07
251,251,St. Vincent and the Grenadines,VCT,"Population, total",SP.POP.TOTL,8.094900e+04,8.214200e+04,8.320600e+04,8.416700e+04,8.506900e+04,...,1.091650e+05,1.092530e+05,1.093150e+05,1.093410e+05,1.093280e+05,1.093200e+05,1.093570e+05,1.094550e+05,1.096430e+05,1.098970e+05
252,252,"Venezuela, RB",VEN,"Population, total",SP.POP.TOTL,8.146847e+06,8.461685e+06,8.790589e+06,9.130349e+06,9.476252e+06,...,2.814170e+07,2.858732e+07,2.902803e+07,2.946329e+07,2.989308e+07,3.031785e+07,3.073838e+07,3.115513e+07,3.156818e+07,3.197706e+07
253,253,British Virgin Islands,VGB,"Population, total",SP.POP.TOTL,8.033000e+03,8.155000e+03,8.298000e+03,8.452000e+03,8.627000e+03,...,2.560400e+04,2.644700e+04,2.722400e+04,2.790100e+04,2.850900e+04,2.905600e+04,2.958800e+04,3.011300e+04,3.066100e+04,3.119600e+04
254,254,Virgin Islands (U.S.),VIR,"Population, total",SP.POP.TOTL,3.250000e+04,3.430000e+04,3.500000e+04,3.980000e+04,4.080000e+04,...,1.083990e+05,1.084050e+05,1.083580e+05,1.082920e+05,1.081910e+05,1.080440e+05,1.078840e+05,1.077100e+05,1.075100e+05,1.072680e+05
255,255,Vietnam,VNM,"Population, total",SP.POP.TOTL,3.267063e+07,3.366677e+07,3.468416e+07,3.572209e+07,3.678098e+07,...,8.670780e+07,8.756541e+07,8.847251e+07,8.943664e+07,9.045188e+07,9.149772e+07,9.254492e+07,9.357157e+07,9.456907e+07,9.554080e+07
256,256,Vanuatu,VUT,"Population, total",SP.POP.TOTL,6.369900e+04,6.571300e+04,6.780800e+04,6.996400e+04,7.213100e+04,...,2.253400e+05,2.307850e+05,2.362950e+05,2.418710e+05,2.474850e+05,2.531420e+05,2.588500e+05,2.646030e+05,2.704020e+05,2.762440e+05
257,257,World,WLD,"Population, total",SP.POP.TOTL,3.032160e+09,3.073369e+09,3.126510e+09,3.191786e+09,3.257460e+09,...,6.766297e+09,6.849569e+09,6.932870e+09,7.014984e+09,7.099558e+09,7.185138e+09,7.271323e+09,7.357559e+09,7.444157e+09,7.530360e+09
258,258,Samoa,WSM,"Population, total",SP.POP.TOTL,1.086460e+05,1.121190e+05,1.157880e+05,1.195610e+05,1.233540e+05,...,1.835260e+05,1.848260e+05,1.862050e+05,1.876650e+05,1.891940e+05,1.907570e+05,1.922900e+05,1.937590e+05,1.951250e+05,1.964400e+05
259,259,Kosovo,XKX,"Population, total",SP.POP.TOTL,9.470000e+05,9.660000e+05,9.940000e+05,1.022000e+06,1.050000e+06,...,1.747383e+06,1.761474e+06,1.775680e+06,1.791000e+06,1.805200e+06,1.824100e+06,1.821800e+06,1.801800e+06,1.816200e+06,1.830700e+06
260,260,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5.172135e+06,5.260501e+06,5.351799e+06,5.446063e+06,5.543339e+06,...,2.235639e+07,2.297493e+07,2.360678e+07,2.425221e+07,2.490997e+07,2.557632e+07,2.624633e+07,2.691621e+07,2.758421e+07,2.825042e+07
261,261,South Africa,ZAF,"Population, total",SP.POP.TOTL,1.745686e+07,1.792067e+07,1.840161e+07,1.889928e+07,1.941298e+07,...,5.041213e+07,5.097082e+07,5.158466e+07,5.226352e+07,5.299821e+07,5.376740e+07,5.453957e+07,5.529122e+07,5.601547e+07,5.671716e+07
262,262,Zambia,ZMB,"Population, total",SP.POP.TOTL,3.044846e+06,3.140264e+06,3.240587e+06,3.345145e+06,3.452942e+06,...,1.308252e+07,1.345642e+07,1.385003e+07,1.426476e+07,1.469994e+07,1.515321e+07,1.562097e+07,1.610059e+07,1.659139e+07,1.709413e+07
263,263,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3.747369e+06,3.870756e+06,3.999419e+06,4.132756e+06,4.269863e+06,...,1.355847e+07,1.381060e+07,1.408632e+07,1.438665e+07,1.471083e+07,1.505451e+07,1.541168e+07,1.577745e+07,1.615036e+07,1.652990e+07